### ISSUE TITLE
请问这个组件有demo吗？

### ISSUE THREAD

**Issue by callELPSYCONGROO** [TIGERB/easy-vue#17]
你好！我是vue初学者，想用这个插件实现滑动分页，请问一下有使用demo的源码吗？

**Comment by TIGERB** [comment]
master 代码即可

**Comment by HiZhaoxiaoyang** [comment]
请问你这玩意哪里值700star？怎么刷的。

**Comment by TIGERB** [comment]
哈哈 你想多了 文章都没发过 项目搞的早了 vue刚出来都搞了 可能搞的早的原因吧 当时demo也少～
