### ISSUE TITLE
'opencollective-postinstall' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by NewbilityLv** [TIGERB/easy-vue#20]
clone到本地后，运行yarn install 一直报下面这个错误。然后试了试cnpm 和npm 也是如此
> opencollective-postinstall

'opencollective-postinstall' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! easy-vue@0.7.2 postinstall: `opencollective-postinstall`
npm ERR! Exit status 1

**Comment by zilan920** [comment]
npm install --save opencollective-postinstall
这个好像是个捐赠的包还是啥

**Comment by TIGERB** [comment]
看起来是 捐赠的包

**Comment by TIGERB** [comment]
修复了～

**Comment by wangshizhong** [comment]
> 修复了～

如何修复的我这也有这个包，但是这个包安装上以后就运行不起来，可以去掉吗

**Comment by TIGERB** [comment]
https://github.com/TIGERB/easy-vue/commit/7b5fa2b2a447b727f8c364cd40d035ea0b76de8c#diff-8ee2343978836a779dc9f8d6b794c3b2
