### ISSUE TITLE
discuss讨论

### ISSUE THREAD

**Issue by andyComeOn** [TIGERB/easy-vue#5]
这个你说的步骤，第三步怎么启的服务，一般不都是在命令行输入 npm  server.js  之类的文件吗？

**Comment by TIGERB** [comment]
我服务是用PHP脚本模拟的，需要PHP环境～

**Comment by andyComeOn** [comment]
原来是这样，我在你package.json中没有找到其服务的指令，就issuse啦。 同样谢谢。

**Comment by TIGERB** [comment]
哦哦，没事～ 

客气～

互相学习～
