### ISSUE TITLE
npm run test 报错

### ISSUE THREAD

**Issue by wenrouzei** [TIGERB/easy-vue#9]
`$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle easy-vue@0.7.0~pretest: easy-vue@0.7.0
6 silly lifecycle easy-vue@0.7.0~pretest: no script for pretest, continuing
7 info lifecycle easy-vue@0.7.0~test: easy-vue@0.7.0
8 verbose lifecycle easy-vue@0.7.0~test: unsafe-perm in lifecycle true
9 verbose lifecycle easy-vue@0.7.0~test: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\phpStudy\WWW\test\easy-vue\node_modules\.bin;C:\Users\Administrator\bin;F:\Program Files\Git\mingw64\bin;F:\Program Files\Git\usr\local\bin;F:\Program Files\Git\usr\bin;F:\Program Files\Git\usr\bin;F:\Program Files\Git\mingw64\bin;F:\Program Files\Git\usr\bin;C:\Users\Administrator\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\NetSarang;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;D:\phpStudy\php\php-7.0.12-nts;D:\phpStudy\MySQL\bin;C:\Program Files (x86)\Subversion\bin;C:\Program Files\nodejs;C:\Program Files (x86)\sqlite;F:\Program Files\Redis;C:\ProgramData\ComposerSetup\bin;D:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Yarn\bin;F:\Program Files\Git\cmd;F:\Program Files\Git\mingw64\bin;F:\Program Files\Git\usr\bin;C:\Users\Administrator\AppData\Roaming\npm;C:\Users\Administrator\AppData\Roaming\Composer\vendor\bin;C:\Users\Administrator\AppData\Local\Yarn\.bin;F:\Program Files\Git\usr\bin\vendor_perl;F:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle easy-vue@0.7.0~test: CWD: D:\phpStudy\WWW\test\easy-vue
11 silly lifecycle easy-vue@0.7.0~test: Args: [ '/d /s /c',
11 silly lifecycle   'DOMAIN=http://localhost:8080 webpack --progress -d --colors && DOMAIN=http://localhost:8080 webpack-dev-server --content-base ./' ]
12 silly lifecycle easy-vue@0.7.0~test: Returned: code: 1  signal: null
13 info lifecycle easy-vue@0.7.0~test: Failed to exec test script
14 verbose stack Error: easy-vue@0.7.0 test: `DOMAIN=http://localhost:8080 webpack --progress -d --colors && DOMAIN=http://localhost:8080 webpack-dev-server --content-base ./`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid easy-vue@0.7.0
16 verbose cwd D:\phpStudy\WWW\test\easy-vue
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error easy-vue@0.7.0 test: `DOMAIN=http://localhost:8080 webpack --progress -d --colors && DOMAIN=http://localhost:8080 webpack-dev-server --content-base ./`
22 error Exit status 1
23 error Failed at the easy-vue@0.7.0 test script 'DOMAIN=http://localhost:8080 webpack --progress -d --colors && DOMAIN=http://localhost:8080 webpack-dev-server --content-base ./'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the easy-vue package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     DOMAIN=http://localhost:8080 webpack --progress -d --colors && DOMAIN=http://localhost:8080 webpack-dev-server --content-base ./
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs easy-vue
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls easy-vue
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by TIGERB** [comment]
估计是window的环境问题，你linux或者mac下跑跑试试～

**Comment by fionagithub** [comment]
同错

**Comment by TIGERB** [comment]
win?
